### ISSUE TITLE
Is LIMIT working?

### ISSUE THREAD

**Issue by deivarezserve** [ethanhann/redisearch-php#12]
Hi Ethan,

when I try to use the limit to paginate my results, I still get 10 documents in my result.

That is my code:
```
$restaurantIndex = new Index($this->redisClient, 'menu-api_local:restaurant-index');
$query = $restaurantIndex
    ->numericFilter('status', 1)
    ->limit(0, 5);
$queryString = ' pizza @city:Nashville @state:3967 @country:225';
$result = $query->search($queryString);
```

My args:
```
array:4 [
  0 => "menu-api_local:restaurant-index"
  1 => " pizza @city:Nashville @state:3967 @country:225"
  2 => "LIMIT 0 5"
  11 => "FILTER status 1 1"
]
```

My rawResults:
```
array:21 [
  0 => 16
  1 => "12529274"
  2 => array:38 [...]
  3 => "12523787"
  4 => array:38 [...]
  5 => "12527644"
  6 => array:38 [...]
  7 => "12526407"
  8 => array:38 [...]
  9 => "12516268"
  10 => array:38 [...]
  11 => "12528032"
  12 => array:38 [...]
  13 => "12532013"
  14 => array:38 [...]
  15 => "12528422"
  16 => array:38 [...]
  17 => "12526111"
  18 => array:38 [...]
  19 => "12528751"
  20 => array:38 [...]
]
```

When I run the same search using redis-cli, I get 5 results, as expected.

> 127.0.0.1:6379> ft.search menu-api_local:restaurant-index pizza @city:Nashville @state:3967 @country:225 LIMIT 0 5 FILTER status 1 1 nocontent
1) (integer) 17
2) "12529274"
3) "12523787"
4) "12527644"
5) "12526407"
6) "12532013"

Any idea what could be the issue? Are you aware of any issue with limit?

I also find curious that I get 16 results using the code and 17 using redis-cli...

**Comment by ethanhann** [comment]
This commit should fix the issue: 62ab7a63bef5d17bc800666087f6a0bd84bd3b41

**Comment by deivarezserve** [comment]
Hi Ethan, thanks.

I am getting this exception on  many of the unit tests though:
Exception: ERR unknown command 'FT.SEARCH'

I can provide additional information as needed.

**Comment by ethanhann** [comment]
That is strange. The unit tests are all passing for me. Are you using the latest version of the RediSearch module?

**Comment by deivarezserve** [comment]
Never mind, today it all passed. It must have been something weird on my installation.

**Comment by deivarezserve** [comment]
Thank you again.
