### ISSUE TITLE
SORTBY support

### ISSUE THREAD

**Issue by deivarezserve** [ethanhann/redisearch-php#13]
Implement SORTBY support, as per http://redisearch.io/Sorting/

**Comment by deivarezserve** [comment]
Hi @ethanhann , I am working on that now. Will send a PR when done. 😄

**Comment by deivarezserve** [comment]
Is it ok if I create a new index inside the test case? Or can I add a sortable field to the one you created in BuilderTest setUp? Please let me know what you prefer.

**Comment by deivarezserve** [comment]
https://github.com/ethanhann/redisearch-php/pull/14

**Comment by ethanhann** [comment]
It is ok to create a new index in a test case if the one in the setup function doesn't work for the new test case.
