### ISSUE TITLE
Score issue

### ISSUE THREAD

**Issue by deivarezserve** [ethanhann/redisearch-php#17]
Hello,

I am creating a document and setting its score, but the raw command sent to Redis is sending score 1.0.

`$document = (new Document())->setId(123456);`
`// Add score to document.`
`$document->setScore(0.3);`
`$document->name = new TextField('name', 'test doc');`
`$index->add($document);`

Arguments sent to FT.ADD:
`[2017-09-06 23:33:49] local.DEBUG: array (`
`  0 => 'test-index',`
`  1 => '123456',`
`  2 => 1.0,`
`  3 => 'FIELDS',`
`  4 => 'name',`
`  5 => 'test doc',`
`)`

I tried to mimic the code from the tests but I'm not sure I am using the right function to set the score. Please let me know if I am doing something wrong.

**Comment by ethanhann** [comment]
This should be resolved in 194c02dd198a351d9c8130783371db3bfd09a18d. Please keep in mind that I changed the API a bit (see commit message), but the example you gave should work now. Short story: I had a couple of different ideas going on with the document builder. I ended up getting rid of the document builder and added a factory instead.
