### ISSUE TITLE
Geofilter changes introduced by RediSearch v0.21.1

### ISSUE THREAD

**Issue by deivarezserve** [ethanhann/redisearch-php#19]
Hi Ethan,

have you seen RediSearch latest release?

https://github.com/RedisLabsModules/RediSearch/releases/tag/v0.21.1

It seems we may need to implement some adjustments to use the new syntax for geofilters. Any plans on when to implement it?

Kind regards,

**Comment by dvirsky** [comment]
@deivarezserve note that:

a. It's not urgent, I deliberately didn't disable GEOFILTER so I won't break anyone's code. 
b. The new method does the filtering directly in the query string.

I think it's time to make the builder a bit more flexible and make it build the query string and not only the request parameters.

**Comment by dvirsky** [comment]
BTW @deivarezserve and @ethanhann, do you think it's time that we open a forum for RediSearch users and client developers? I feel like github issues are not enough, and the community is starting to gain enough momentum to justify this. What do you guys think?

**Comment by deivarezserve** [comment]
Oh, that is great, thanks @dvirsky !

About the forum, I think it is a great idea! 😄 
If you need any help setting it up, we can probably help you out, right @mattboban ?

**Comment by ethanhann** [comment]
@deivarezserve Dvir made me aware of the change about a month ago. I created #8 to remind myself to do it, but it isn't a high priority for me at the moment.

@dvirsky I would participate in a forum if one were available.

**Comment by ethanhann** [comment]
a179aea3a70ea1ca6f0a3d091caaf581f7e402a6
