### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by mstaack** [ethanhann/redisearch-php#2]
some ideas:

- [x] remove RediSearch dir and let the namespace be handled by composer psr4 loader
- [x] ensure consistency via phpcsfixer etc..
- [x] allow travis test running, should be easy to set everything up..basically compile & run
- [x] more tests..
- [x] We probably should allow different redis clients via adapter, the current solutions feels kinda hacky

willing to do prs ;)

nice one!

(just found your laravel scout wrapper...awesome idea!)

cheers max

**Comment by ethanhann** [comment]
All good ideas. I look forward to any PRs you want to do.

The Laravel Scout driver is very primitive (and untested), but something I plan to build out a bit when I get a few more cycles.

**Comment by mstaack** [comment]
yeah nice! will get back to you soon....

**Comment by ethanhann** [comment]
I took care of the easy stuff. The issue with using a CI server is that probably none of them have an unstable build of Redis with the RediSearch module available. I added a Robo (PHP task runner) file and a note in the README on contributing. Unless I'm wrong in my assumption, that's probably good enough for now.

Re: Redis clients - I wanted to avoid building out lots of adapter code, but at the same time I'm not in love with how I did it. If you have a clean solution in mind I'd be interested to see it.

**Comment by mstaack** [comment]
i would use docker probably with travis... nice work !

**Comment by ethanhann** [comment]
@mstaack I tried building on Travis, but I am running into a consistent issue that is only happening in Travis. Any idea what is causing this?

For PHP 7.1, I get this error: "RedisException: Connection lost and socket is in MULTI/watching mode"
Travis log: https://travis-ci.org/ethanhann/redisearch-php/jobs/268807364#L578

For PHP 7.0, I get this error: "RedisException: protocol error, got '�' as reply-type byte"
Travis log: https://travis-ci.org/ethanhann/redisearch-php/jobs/268807363#L584

**Comment by ethanhann** [comment]
I think the build is failing because Travis is using an older version of the phpredis extension.

**Comment by ethanhann** [comment]
The test are passing on Travis now because the Predis library is defaulted to, i.e. the tests that fail with phpredis are no longer being run. Until Travis updates to the latest version of the extension there is no point to running the tests with phpredis as well.

**Comment by rafaelbeckel** [comment]
About the last item: 

Predis is abandoned, now we really need that adapter to support more clients, or at least hardcode a more up-to-date client like this one https://github.com/cheprasov/php-redis-client

**Comment by ethanhann** [comment]
I add adapter code. There are client adapters for Predis, PhpRedis, and the Cheprasov client. They all extend [AbstractRedisClient](https://github.com/ethanhann/redisearch-php/blob/master/src/Redis/AbstractRedisClient.php) which implements [RedisClientInterface](https://github.com/ethanhann/redisearch-php/blob/master/src/Redis/RedisClientInterface.php). An additional adapter can be created by extending AbstractRedisClient or by implementing RedisClientInterface if needed for some reason.
