### ISSUE TITLE
Exception raised in inFields function

### ISSUE THREAD

**Issue by pdavide** [ethanhann/redisearch-php#21]
If you simply call `inFields` function on a `Index` or `Builder` object like this
```
$index->inFields(2, ['field_1', 'field_2']);
```
an ErrorException is raised.
ErrorException: Array to string conversion.
https://github.com/ethanhann/redisearch-php/blob/d3fe4bb33e2aa2ec876146d8c0d1a9531cc3a22f/src/Query/Builder.php#L51

**Comment by ethanhann** [comment]
See #23

**Comment by pdavide** [comment]
Well done.

**Comment by ethanhann** [comment]
Thanks for the contribution
