### ISSUE TITLE
Do I need to recreate the index everytime?

### ISSUE THREAD

**Issue by rafaelbeckel** [ethanhann/redisearch-php#25]
Docs are not clear about how to retrieve an existing schema instance. Do I need to always recreate it everytime I need to search?

For example would I need to do this: 
~~~php
$bookIndex = new Index();

$bookIndex->addTextField('title')
    ->addTextField('author')
    ->addNumericField('price')
    ->addNumericField('stock')
    ->create();

$result = $bookIndex->search('two cities');
~~~

Instead of:
~~~php
$bookIndex = new Index('some_key');

$result = $bookIndex->search('two cities');
~~~

**Comment by rafaelbeckel** [comment]
OK, now I have spotted in the Index Interface these two methods:
~~~php
    public function getIndexName(): string;
    public function setIndexName(string $indexName): IndexInterface;
~~~

I suppose they serve my intended purpose. I will PR them in the docs when I can.

**Comment by rvencu** [comment]
If possible, please give an example of
- listing existing indexes
- dropping an index by its name
