### ISSUE TITLE
The field is not a property in the index

### ISSUE THREAD

**Issue by gorlovka** [ethanhann/redisearch-php#29]
I tried to follow documentation . This is what I have: 

        $redis = (new RedisClientAdapter())->connect('redissearch', 6379);

        $bookIndex = new Index($redis);

        $bookIndex->drop();

        $bookIndex->addTextField('title')
              ->create();

        $bookIndex->add([
           new TextField('title', 'Tale of Two Cities'),
        ]);

It gives the following error:

http://kagda.ru/i/160116696Selection16548_26-04-2018-13:14:03_1601.png

I tried to debug it.

First checking this file: 
http://kagda.ru/i/dd01dd834Selectiondd780_26-04-2018-13:20:08_dd01.png

**Comment by ethanhann** [comment]
I'm not sure how you're getting that error. I tested locally by copy/pasting your code and I'm unable to reproduce. What version of PHP and RediSearch-PHP are you using?
