### ISSUE TITLE
Improper search query output format with multiple filters

### ISSUE THREAD

**Issue by matijaboban** [ethanhann/redisearch-php#30]
Predis: 1.1.1
Redis: 4.0.8
PHP: 7.2.3
OS: Ubuntu 16.04.4

I've come to this issue again, after not utilizing the latest version of the library for some time, due to a custom build requirements. First of all great work @ethanhann 

I do have an inconsistent to either report or to get clarification on.

When building a query like:
`$this->index->numericFilter('city_id', 1596)->numericFilter('country_id', 37)->search('@name: Sons');`
the search results are inconsistant and actually include results out of the range of numerical filters. 

This is due to the raw command output:
`"FT.SEARCH" "restaurants:search" "@name: Sons" "@city_id:[1596 1596]" "@country_id:[37 37]"`
as the query parametars are grouped separatly.

The actually raw command should be:
`"FT.SEARCH" "restaurants:search" "@name: Sons @city_id:[1596 1596] @country_id:[37 37]"` as this seams to provide propper exclusion/filtering

I can, of course, accomplish this by using raw expression:
`$this->index->search('@name: Sons @city_id:[1596 1596] @country_id:[37 37]');`
but I'm wondering if this is expected behavior or have I missed something in the documentation/source code review.

**Comment by matijaboban** [comment]
@ethanhann I've traced this to a deeper issue with the Predis library itself and opened a ticket at https://github.com/nrk/predis/issues/501

For dependency reasons, I'm not in a position to consider a move to phpredis at this time.

@dvirsky fully aware this is not an issue with the underlying Redis/module functionality, but if you have any insight, it would be helpful and much appreciated.

**Comment by ethanhann** [comment]
I could be wrong, but from what I can tell Predis isn't maintained anymore. This is a less popular, but maintained lib: https://github.com/cheprasov/php-redis-client

**Comment by ethanhann** [comment]
This behavior changed in v1.3. Multiple numeric filters should probably work now.
