### ISSUE TITLE
Adding a document to a non-existing index does not yield a proper exception

### ISSUE THREAD

**Issue by matijaboban** [ethanhann/redisearch-php#31]
When adding a document via the add(), for instance:

`$this->index->add($doc);`

in a situation when an index is not set on redis, **UnknownIndexNameException** is **not** raised, instead a (bool) true is returned.

The exception is properly raised with other methods in the same situations, for instance:
`$this->index->info()`

**Comment by ethanhann** [comment]
This was a Predis-specific issue where Predis doesn't return the error response message in the same case as the other clients. This has been resolved in release 1.1.2.
