### ISSUE TITLE
Are Tag fields currently supported?

### ISSUE THREAD

**Issue by jersak** [ethanhann/redisearch-php#32]
I've been trying to find a way to use [Tag fields ](https://github.com/RedisLabsModules/RediSearch/blob/745115c0e472e98855411d35d7a271d2385ed0ec/docs/Tags.md) but I couldn't find it in the docs or in the code. Is it currently supported and, if not, do you plan on adding it in the near future?

**Comment by morphers82** [comment]
Its pretty easy to fork and add support for it.

**Comment by ethanhann** [comment]
go for it
