### ISSUE TITLE
Utilizing the Laravel Redis Sentinel client

### ISSUE THREAD

**Issue by matijaboban** [ethanhann/redisearch-php#33]
Hi @ethanhann just looking at utilizing your lib thru Laravel Drivers for Redis Sentinel (https://github.com/monospice/laravel-redis-sentinel-drivers), before I get into this, is there any easy way to link it to the predis connector directly, or would an additional adapter need to be written?

Thanks for any insight.

**Comment by ethanhann** [comment]
It sounds like you want to use the Redis client Laravel provides. You would need to hook it into a ClientAdapter like this: https://github.com/ethanhann/Laravel-RediSearch/blob/master/src/RediSearchServiceProvider.php#L17
