### ISSUE TITLE
Laravel Scout 5.x support?

### ISSUE THREAD

**Issue by CodeCooler** [ethanhann/redisearch-php#36]
When attempting to install laravel-redisearch in a new project, it seems it does support the current release of Scout (5.0):

```  
ethanhann/laravel-redisearch 0.7.1 requires laravel/scout ^3.0|^4.0 -> satisfiable by laravel/scout[3.0.x-dev, 4.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v4.0.0, v4.0.1, v4.0.2, v4.0.3, v4.0.4]
```

For now, I've gone back to Scout 4.0.4, but figured I'd make note of this. Thanks!

**Comment by phoenixg** [comment]
Please support latest Laravel scout +1

**Comment by SoGooDFR** [comment]
Pls update Laravel-RediSearch...

**Comment by phoenixg** [comment]
What's the version match for the latest feature?

```
"ethanhann/laravel-redisearch": "^0.1.0",
"ethanhann/redisearch-php": "^1.3.0",
```

This doesn't match.

`    - The requested package ethanhann/laravel-redisearch ^1.3.0 exists as ethanhann/laravel-redisearch[0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.7.1, dev-master] but these are rejected by your constraint.`

**Comment by SoGooDFR** [comment]
I can't wait for the update... @phoenixg Simply use phpredis as php extension.

**Comment by phoenixg** [comment]
@SoGooDFR Why phpredis, how can I use this to solve the problem?

**Comment by ethanhann** [comment]
Should re resolved by https://github.com/ethanhann/Laravel-RediSearch/pull/4
