### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by mosfetish** [ethanhann/redisearch-php#39]
The Getting Started page...

http://www.ethanhann.com/redisearch-php/

...shows incorrect namespacing in the use statements.

For instance:

use Ehann\RediSearch\Redis\PhpRedisAdapter;

Should be:

use Ehann\RedisRaw\PhpRedisAdapter;

**Comment by ethanhann** [comment]
Resolved: https://github.com/ethanhann/redisearch-php/commit/556c91120861f9c946cf848c9421918953590921
