### ISSUE TITLE
Documentation for "Filtering Geo Fields" is wrong

### ISSUE THREAD

**Issue by ecordani** [ethanhann/redisearch-php#40]
The documentation related to Filtering Geo Fields is wrong ([http://www.ethanhann.com/redisearch-php/searching/#filtering-geo-fields](http://www.ethanhann.com/redisearch-php/searching/#filtering-geo-fields)), the text is the copy of the section above (Filtering Numeric Fields).

**Comment by ethanhann** [comment]
Resolved: https://github.com/ethanhann/redisearch-php/commit/b8047d385650393fb2c83c763eff4ea6fd0d82b6
