### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Rudis1261** [ethanhann/redisearch-php#5]
Hey man, I wonder if you can please include the `use /so/on/so/on` in the examples? I can't seem to get anything to load.

Please

**Comment by Rudis1261** [comment]
An example usage:
```
require './vendor/autoload.php';

use Ehann\RediSearch\Index;
use Ehann\RediSearch\Fields\TextField;
use Ehann\RediSearch\Fields\NumericField;
use Ehann\RediSearch\Redis\RedisClient;

var_dump(new Index());
```

Then I get this:
`Fatal error: Uncaught Error: Class 'Ehann\RediSearch\Index' not found in /usr/share/nginx/html/tvt2/index.php:30 Stack trace: #0 {main} thrown in /usr/share/nginx/html/tvt2/index.php on line 30`

And the another example:
```
require './vendor/autoload.php';

use Ehann\RediSearch\Index;
use Ehann\RediSearch\Fields\TextField;
use Ehann\RediSearch\Fields\NumericField;
use Ehann\RediSearch\Redis\RedisClient;

var_dump($redis = new RedisClient('Redis', 'redis-search', 6380, 0, ''));
```

And the response:
```Fatal error: Uncaught Error: Class 'Ehann\RediSearch\Redis\RedisClient' not found in /usr/share/nginx/html/tvt2/index.php:30 Stack trace: #0 {main} thrown in /usr/share/nginx/html/tvt2/index.php on line 30```

**Comment by ethanhann** [comment]
I ran both your examples successfully. It seems like something is wrong with your vendor directory/autoload file. You can try deleting ./vendor and running composer install. Maybe that will resolve the issue. Which version of PHP are you running?

**Comment by Rudis1261** [comment]
Hi Ethan,

So weird man, I checked the vendor directory and the files were there. 

I am running php 7.1

Cheers,
Rudi

**Comment by ethanhann** [comment]
I tested with PHP 7.1 as well - so that shouldn't be a problem.

Even if the files are in vendor, the autoload file that maps the classes might be messed up for some reason. It happens on occasion, independent of this library. If that isn't the issue then unfortunately I am not sure what the problem is.

**Comment by ethanhann** [comment]
Added import statements in docs.
