### ISSUE TITLE
Issue FT.ALTER ALIAS command

### ISSUE THREAD

**Issue by garygreen** [ethanhann/redisearch-php#50]
Is it currently possible to issue an `FT.ALTER` command for adding / removing aliases?

Our use case is we want to create a new index with a fresh schema, reindex in the data and then alias the index to point to that new data. This allows us to instantly switch between indexes with zero downtime.

**Comment by ethanhann** [comment]
I added support for aliasing in release 1.9.0: http://www.ethanhann.com/redisearch-php/indexing/#aliasing

This should make the zero downtime index migration process possible.
