### ISSUE TITLE
Master with tag field support is not released as a version

### ISSUE THREAD

**Issue by Pat-Groesser** [ethanhann/redisearch-php#51]
Hey, 

I was wondering why on the lastest version of master 2month ago you added tag filter support but its still not yet released as a version ? 

Thanks

**Comment by axute** [comment]
i am missing the tag filter also in latest version.

**Comment by loiclaloux** [comment]
Me too. 
Thanks

https://github.com/ethanhann/redisearch-php/compare/1.5.0...master

**Comment by ethanhann** [comment]
I forgot to merge the feature branch before making release `1.5.0`. Release `1.6.0` should now have the tag search functionality.
