### ISSUE TITLE
Fields not known when using an existing index

### ISSUE THREAD

**Issue by ghdi** [ethanhann/redisearch-php#59]
Hi,

When I use an __existing__ index that has been previously created, meaning that my code only sets the index' name,  and I use the $index->makeDocument() method, the resulting document does not know any of the index' fields.

Is this intended behavior or am I missing something?

To overcome this, I currently add all text fields to the existing index  before I issue a makeDocument().

Examples (lets assume the index' documents have one text field called name):

###  **Example where fields are not known:** 
....

$index = new \Ehann\RediSearch\Index($predisAdapter);

$index->setIndexName('test');

$document = $index->makeDocument()

$document->name->setValue('hello world!'); # <== throws exception

 ### **Example where fields are known:** 
....

$index = new \Ehann\RediSearch\Index($predisAdapter);

$index->setIndexName('test');

$index->addTextField('name')

$document = $index->makeDocument()

$document->name->setValue('hello world!'); # <== this works as intended

Regards,

Edwin

**Comment by amir2008k** [comment]
I have the same problem with rediSearch:

When I run server and execute the codes, I don't recieve any result. result of search is empty!

After second executing rediSearch returned this error:

Ehann\RediSearch\Exceptions\FieldNotInSchemaException: The field is not a property in the index. title in C:\xampp\htdocs\redis\vendor\ethanhann\redisearch-php\src\Document\AbstractDocumentFactory.php on line 27


Ehann\RediSearch\Index->add( ) | ...\redi.php:35
Ehann\RediSearch\Index->arrayToDocument( ) | ...\Index.php:506
Ehann\RediSearch\Document\AbstractDocumentFactory::makeFromArray( ) | ...\Index.php:496

Can anyone help me?
