### ISSUE TITLE
Can't create index

### ISSUE THREAD

**Issue by quevlu** [ethanhann/redisearch-php#66]
Hello, I have a problem with the next code:

```
$key = 'database.connections.redis.';
$this->redis = (new PredisAdapter())->connect(config($key . "host"), config($key . "port"), 1);
$bookIndex = new Index($this->redis, 'wop');
$bookIndex->addTextField('location')->create();
```
When I execute this code, I have this error:

 ERR unknown command `FT.CREATE`, with args beginning with: `wop`, `SCHEMA`, `location`, `TEXT`, `WEIGHT`, `1`,

**Comment by byinff** [comment]
This developers mama mia : https://oss.redislabs.com/redisearch/index.html

**Comment by mislavjakopovic** [comment]
Looks like you didn't have redisearch module enabled:
 `redis-server --loadmodule /usr/lib/redis/modules/redisearch.so`

**Comment by quevlu** [comment]
@mislavjakopovic Yeah, This was the problem and it has solved
