### ISSUE TITLE
How to set different connection to RediSearch ?

### ISSUE THREAD

**Issue by BakuDev** [ethanhann/redisearch-php#68]
I'm unable to set another connection to redis for this library in Laravel-support package.
Please advise how to override default Laravel's connection?

**Comment by BakuDev** [comment]
I also tried to override connect method in  ClientAdapter, but it doesn't work. 
Queued redisearch jobs always use default Laravel connection to Redis.

```
public function connect($hostname = '127.0.0.1', $port = 6379, $db = 0, $password = null): RedisRawClientInterface
    {
        $this->redis->connect('192.168.1.99', 6379, 5);

        return $this;
    }
```

**Comment by shyim** [comment]
Why are you not passing other connection informations here?
