### ISSUE TITLE
When the tags contain "-" it will throw an syntax error

### ISSUE THREAD

**Issue by shyim** [ethanhann/redisearch-php#70]
Syntax error at offset 33 near

**Comment by ghdi** [comment]
This has nothing to do with redisearch-php but with redisearch itself. See https://oss.redislabs.com/redisearch/Tags/#multi-word_tags_and_escaping

When you escape the dash, the syntax error will disappear.

**Comment by shyim** [comment]
Yes, but should this Library not do that for me? :thinking:
