### ISSUE TITLE
Remove FILTER argument and use only the embedded syntax

### ISSUE THREAD

**Issue by ethanhann** [ethanhann/redisearch-php#8]
@dvirsky What is the embedded syntax you referenced in your [comment](https://github.com/ethanhann/redisearch-php/issues/7#issuecomment-325436513)? I don't see anything about it in the docs. Is that a new feature?

**Comment by dvirsky** [comment]
Yes, I haven't implemented it yet, see https://github.com/RedisLabsModules/RediSearch/issues/136

**Comment by ethanhann** [comment]
a179aea3a70ea1ca6f0a3d091caaf581f7e402a6
