### ISSUE TITLE
Unit tests require PhpRedis

### ISSUE THREAD

**Issue by deivarezserve** [ethanhann/redisearch-php#9]
Hi Ethan,

First of all, thank you for your work on this library.

Second, I have a question... I ran into an error while trying to run the unit tests:
Error: Class 'Redis' not found in /var/www/lib-redisearch-php/src/Redis/RedisClient.php on line 14

This happened because I am using Predis and the way the unit tests are written, PhpRedis is actually required to run any tests (because AbstractTestCase uses RedisClient which has Redis as default class). 

Shouldn't PhpRedis be a dev dependency on composer then?

**Comment by ethanhann** [comment]
Good call. I've been working on unit tests today. I'll add it.

**Comment by ethanhann** [comment]
But keep in mind that PhpRedis is a PHP extension and will not be installed by composer. Composer will just complain about it not being available.

**Comment by deivarezserve** [comment]
Well, it will give an indication of where the problem is at least... 
Thank you, Ethan!

**Comment by deivarezserve** [comment]
Another alternative would be to make it configurable:
https://github.com/DigitalTown/lib-redisearch-php/commit/28cb95a076fab8238068fa0a6f243eaaf5a2d660

Just an idea, of course...

**Comment by ethanhann** [comment]
I went with your suggestion to make the library configurable. I also used the @requires tag to mark the PhpRedis-specific tests as requiring the extension. This gives a more user friendly message in the phpunit output.

**Comment by deivarezserve** [comment]
Awesome, thanks!
